### ISSUE TITLE
Externalize more parameters for the LLM invocation

### ISSUE THREAD

**Issue by avi44522** [pberlandier/watsonxai-from-odm#1]
from my test, the project-ID needs to be defined for a successful execution.
And it would be also good to externalize the model name.

So the following 2 lines in WatsonxAIRunner should be replaced by variables in the decision project, especially the first one which is causing a runtime error: 
	private String projectId = "<project-id>";
	private String modelId = "google/flan-ul2";

**Comment by pberlandier** [comment]
Keeping variables limited to URL and API Key (which are at the level of the watsonx.ai instance).
Added the configuration of the project id and the model id through initial action in the ruleflow (see "determine review sentiment" rule task).
```
set the project id of 'the LLM service' to "2209af66-226e-400a-b72e-5efe778e0abb" ;
set the model id of 'the LLM service' to "google/flan-ul2" ;
set the repetition penalty of 'the LLM service' to 1.05 ;
```
Other model parameters are also available through other setter methods.
